-- =====================================================
-- SALMA ACCESORIOS - SCRIPT DE INICIALIZACION
-- Compatible con las entidades Java actuales del proyecto.
--
-- Uso:
-- 1. Crear la base de datos: salma_accesorios
-- 2. Ejecutar este script completo.
-- 3. Iniciar la app con: .\mvnw.cmd spring-boot:run
-- =====================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =====================================================
-- LIMPIEZA
-- =====================================================

DROP TABLE IF EXISTS review_images CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS return_requests CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS favorites CASCADE;
DROP TABLE IF EXISTS cart_items CASCADE;
DROP TABLE IF EXISTS carts CASCADE;
DROP TABLE IF EXISTS product_images CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS site_content CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS cities CASCADE;

DROP FUNCTION IF EXISTS refresh_product_average_rating() CASCADE;
DROP FUNCTION IF EXISTS create_cart_for_new_user() CASCADE;

-- =====================================================
-- TABLAS
-- =====================================================

CREATE TABLE cities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    CONSTRAINT uk_city_name UNIQUE (name),
    CONSTRAINT chk_cities_name CHECK (length(trim(name)) >= 2)
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    slug VARCHAR(100) NOT NULL,
    CONSTRAINT uk_categories_name UNIQUE (name),
    CONSTRAINT uk_categories_slug UNIQUE (slug),
    CONSTRAINT chk_categories_name CHECK (length(trim(name)) >= 3),
    CONSTRAINT chk_categories_slug CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(60) NOT NULL,
    second_name VARCHAR(60),
    first_last_name VARCHAR(60) NOT NULL,
    second_last_name VARCHAR(60) NOT NULL,
    email VARCHAR(120) NOT NULL,
    username VARCHAR(40) NOT NULL,
    phone VARCHAR(10) NOT NULL,
    password VARCHAR(255) NOT NULL,
    city_id BIGINT NOT NULL,
    address VARCHAR(160) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'CLIENTE',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_phone UNIQUE (phone),
    CONSTRAINT fk_users_city FOREIGN KEY (city_id) REFERENCES cities (id),
    CONSTRAINT chk_users_role CHECK (role IN ('ADMIN', 'CLIENTE')),
    CONSTRAINT chk_users_phone CHECK (phone ~ '^3[0-9]{9}$')
);

CREATE TABLE site_content (
    id BIGINT PRIMARY KEY,
    hero_eyebrow VARCHAR(120) NOT NULL DEFAULT 'ORIGINAL DESIGNS',
    hero_title VARCHAR(120) NOT NULL DEFAULT 'Nueva coleccion 2026',
    hero_copy VARCHAR(260) NOT NULL DEFAULT 'Joyeria artesanal, delicada y luminosa para vestir momentos cotidianos con encanto vintage.',
    hero_button_label VARCHAR(80) NOT NULL DEFAULT 'Explorar coleccion',
    hero_image_url VARCHAR(500),
    footer_tagline VARCHAR(160) NOT NULL DEFAULT 'original designs',
    footer_categories_title VARCHAR(80) NOT NULL DEFAULT 'Categorias',
    footer_contact_title VARCHAR(80) NOT NULL DEFAULT 'Contacto',
    whatsapp_text VARCHAR(120) NOT NULL DEFAULT 'WhatsApp +57 3212292317',
    whatsapp_url VARCHAR(500) NOT NULL DEFAULT 'https://wa.me/573212292317',
    instagram_text VARCHAR(120) NOT NULL DEFAULT 'Instagram',
    instagram_url VARCHAR(500) NOT NULL DEFAULT 'https://www.instagram.com/salmaaccesoriosss/?hl=es',
    footer_copyright VARCHAR(120) NOT NULL DEFAULT '2026 Salma Accesorios',
    CONSTRAINT chk_site_content_singleton CHECK (id = 1)
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(1200) NOT NULL,
    price NUMERIC(12, 2) NOT NULL,
    stock INTEGER NOT NULL,
    category_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    featured BOOLEAN NOT NULL DEFAULT FALSE,
    new_collection BOOLEAN NOT NULL DEFAULT FALSE,
    average_rating NUMERIC(3, 2) NOT NULL DEFAULT 0,
    sold_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT chk_products_name CHECK (length(trim(name)) >= 3),
    CONSTRAINT chk_products_description CHECK (length(trim(description)) >= 10),
    CONSTRAINT chk_products_price CHECK (price > 0),
    CONSTRAINT chk_products_stock CHECK (stock >= 0),
    CONSTRAINT chk_products_average_rating CHECK (average_rating >= 0 AND average_rating <= 5),
    CONSTRAINT chk_products_sold_count CHECK (sold_count >= 0)
);

CREATE TABLE product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    alt_text VARCHAR(140) NOT NULL,
    main_image BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_product_images_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT chk_product_images_url CHECK (length(trim(image_url)) >= 3),
    CONSTRAINT chk_product_images_alt_text CHECK (length(trim(alt_text)) >= 3)
);

CREATE TABLE carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    CONSTRAINT uk_carts_user UNIQUE (user_id),
    CONSTRAINT fk_carts_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    selected BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_cart_product UNIQUE (cart_id, product_id),
    CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES carts (id) ON DELETE CASCADE,
    CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT chk_cart_items_quantity CHECK (quantity > 0)
);

CREATE TABLE favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_favorite_user_product UNIQUE (user_id, product_id),
    CONSTRAINT fk_favorites_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_favorites_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    total NUMERIC(12, 2) NOT NULL DEFAULT 0,
    shipping_cost NUMERIC(12, 2) NOT NULL DEFAULT 0,
    shipping_address VARCHAR(160) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_orders_status CHECK (status IN ('PENDIENTE', 'PAGADO', 'ENVIADO', 'ENTREGADO', 'CANCELADO')),
    CONSTRAINT chk_orders_total CHECK (total >= 0),
    CONSTRAINT chk_orders_shipping_cost CHECK (shipping_cost >= 0),
    CONSTRAINT chk_orders_shipping_address CHECK (length(trim(shipping_address)) >= 8)
);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL,
    CONSTRAINT uk_order_product UNIQUE (order_id, product_id),
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT chk_order_items_quantity CHECK (quantity > 0),
    CONSTRAINT chk_order_items_unit_price CHECK (unit_price > 0)
);

CREATE TABLE return_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    reason VARCHAR(500) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'SOLICITADA',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_return_requests_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_return_requests_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_return_requests_status CHECK (status IN ('SOLICITADA', 'EN_REVISION', 'APROBADA', 'RECHAZADA', 'CERRADA')),
    CONSTRAINT chk_return_requests_reason CHECK (length(trim(reason)) BETWEEN 8 AND 500)
);

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    rating INTEGER NOT NULL,
    comment VARCHAR(800) NOT NULL,
    approved BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_review_user_product UNIQUE (user_id, product_id),
    CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_reviews_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT chk_reviews_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT chk_reviews_comment CHECK (length(trim(comment)) BETWEEN 8 AND 800)
);

CREATE TABLE review_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id BIGINT NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    CONSTRAINT fk_review_images_review FOREIGN KEY (review_id) REFERENCES reviews (id) ON DELETE CASCADE,
    CONSTRAINT chk_review_images_url CHECK (length(trim(image_url)) >= 3)
);

-- =====================================================
-- INDICES
-- =====================================================

CREATE INDEX idx_categories_slug ON categories (slug);

CREATE INDEX idx_users_email ON users (email);
CREATE INDEX idx_users_username ON users (username);
CREATE INDEX idx_users_city ON users (city_id);
CREATE INDEX idx_users_enabled ON users (enabled);
CREATE INDEX idx_users_role ON users (role);

CREATE INDEX idx_products_name ON products (name);
CREATE INDEX idx_products_category ON products (category_id);
CREATE INDEX idx_products_featured ON products (featured);
CREATE INDEX idx_products_new_collection ON products (new_collection);
CREATE INDEX idx_products_active ON products (active);
CREATE INDEX idx_products_created_at ON products (created_at DESC);
CREATE INDEX idx_products_sold_count ON products (sold_count DESC);
CREATE INDEX idx_products_average_rating ON products (average_rating DESC);

CREATE INDEX idx_product_images_product ON product_images (product_id);
CREATE UNIQUE INDEX uk_product_one_main_image ON product_images (product_id) WHERE main_image = TRUE;

CREATE INDEX idx_cart_items_selected ON cart_items (selected);
CREATE INDEX idx_cart_items_cart ON cart_items (cart_id);
CREATE INDEX idx_cart_items_product ON cart_items (product_id);

CREATE INDEX idx_favorites_user ON favorites (user_id);
CREATE INDEX idx_favorites_product ON favorites (product_id);

CREATE INDEX idx_orders_user ON orders (user_id);
CREATE INDEX idx_orders_status ON orders (status);
CREATE INDEX idx_orders_created_at ON orders (created_at DESC);

CREATE INDEX idx_order_items_order ON order_items (order_id);
CREATE INDEX idx_order_items_product ON order_items (product_id);

CREATE INDEX idx_return_requests_user ON return_requests (user_id);
CREATE INDEX idx_return_requests_order ON return_requests (order_id);
CREATE INDEX idx_return_requests_status ON return_requests (status);
CREATE INDEX idx_return_requests_created_at ON return_requests (created_at DESC);

CREATE INDEX idx_reviews_product ON reviews (product_id);
CREATE INDEX idx_reviews_user ON reviews (user_id);
CREATE INDEX idx_reviews_approved ON reviews (approved);

CREATE INDEX idx_review_images_review ON review_images (review_id);

-- =====================================================
-- TRIGGERS
-- =====================================================

CREATE OR REPLACE FUNCTION create_cart_for_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO carts (user_id) VALUES (NEW.id)
    ON CONFLICT (user_id) DO NOTHING;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_create_cart_for_new_user
AFTER INSERT ON users
FOR EACH ROW
EXECUTE FUNCTION create_cart_for_new_user();

CREATE OR REPLACE FUNCTION refresh_product_average_rating()
RETURNS TRIGGER AS $$
DECLARE
    affected_product_id BIGINT;
BEGIN
    affected_product_id := COALESCE(NEW.product_id, OLD.product_id);

    UPDATE products
    SET average_rating = COALESCE((
        SELECT ROUND(AVG(rating)::numeric, 2)
        FROM reviews
        WHERE product_id = affected_product_id
          AND approved = TRUE
    ), 0)
    WHERE id = affected_product_id;

    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_reviews_refresh_product_rating
AFTER INSERT OR UPDATE OR DELETE ON reviews
FOR EACH ROW
EXECUTE FUNCTION refresh_product_average_rating();

-- =====================================================
-- DATOS INICIALES
-- =====================================================

INSERT INTO cities (name) VALUES
('Bogota'),
('Medellin'),
('Cali'),
('Barranquilla'),
('Cartagena'),
('Bucaramanga'),
('Pereira'),
('Santa Marta'),
('Manizales'),
('Villavicencio')
ON CONFLICT (name) DO NOTHING;

INSERT INTO categories (name, slug) VALUES
('Collares', 'collares'),
('Pulseras', 'pulseras'),
('Anillos', 'anillos'),
('Llaveros', 'llaveros')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO site_content (
    id, hero_eyebrow, hero_title, hero_copy, hero_button_label, hero_image_url,
    footer_tagline, footer_categories_title, footer_contact_title,
    whatsapp_text, whatsapp_url, instagram_text, instagram_url, footer_copyright
) VALUES (
    1,
    'ORIGINAL DESIGNS',
    'Nueva coleccion 2026',
    'Joyeria artesanal, delicada y luminosa para vestir momentos cotidianos con encanto vintage.',
    'Explorar coleccion',
    '/img/CollarXiomaraFosil.jpeg',
    'original designs',
    'Categorias',
    'Contacto',
    'WhatsApp +57 3212292317',
    'https://wa.me/573212292317',
    'Instagram',
    'https://www.instagram.com/salmaaccesoriosss/?hl=es',
    '2026 Salma Accesorios'
) ON CONFLICT (id) DO UPDATE SET
    hero_eyebrow = EXCLUDED.hero_eyebrow,
    hero_title = EXCLUDED.hero_title,
    hero_copy = EXCLUDED.hero_copy,
    hero_button_label = EXCLUDED.hero_button_label,
    hero_image_url = EXCLUDED.hero_image_url,
    footer_tagline = EXCLUDED.footer_tagline,
    footer_categories_title = EXCLUDED.footer_categories_title,
    footer_contact_title = EXCLUDED.footer_contact_title,
    whatsapp_text = EXCLUDED.whatsapp_text,
    whatsapp_url = EXCLUDED.whatsapp_url,
    instagram_text = EXCLUDED.instagram_text,
    instagram_url = EXCLUDED.instagram_url,
    footer_copyright = EXCLUDED.footer_copyright;

-- Contrasenas:
-- admin@salma.com              -> Admin123*
-- cliente1@salma.com           -> Cliente123*
-- cliente2@salma.com           -> Compra456*
-- laura.mendez@example.com     -> Laura2026*
-- natalia.giraldo@example.com  -> Natalia789*
-- sofia.ramirez@example.com    -> Sofia321*

INSERT INTO users (
    first_name, second_name, first_last_name, second_last_name,
    email, username, phone, password, city_id, address, role, enabled
)
SELECT
    'Admin', NULL, 'Salma', 'Accesorios',
    'admin@salma.com', 'admin', '3000000000',
    '$2a$10$3fsyck4b6o751PYP7i6IY.2ZiPPmX.MLdomn.PXvn5adgNbLjN4v2',
    c.id, 'Calle 1 # 1-1', 'ADMIN', TRUE
FROM cities c
WHERE c.name = 'Bogota'
ON CONFLICT (email) DO NOTHING;

INSERT INTO users (
    first_name, second_name, first_last_name, second_last_name,
    email, username, phone, password, city_id, address, role, enabled
)
SELECT
    'Valentina', 'Mariana', 'Rojas', 'Martinez',
    'cliente1@salma.com', 'cliente1', '3111111111',
    '$2a$10$R808SVGZpR5zrBoe5yma4OznTtu8dpGo0I0cm.57V96Pu7JEsbJ2K',
    c.id, 'Carrera 43A # 10-20', 'CLIENTE', TRUE
FROM cities c
WHERE c.name = 'Medellin'
ON CONFLICT (email) DO NOTHING;

INSERT INTO users (
    first_name, second_name, first_last_name, second_last_name,
    email, username, phone, password, city_id, address, role, enabled
)
SELECT
    'Camila', 'Sofia', 'Gomez', 'Torres',
    'cliente2@salma.com', 'cliente2', '3222222222',
    '$2a$10$n7tncdR8fx1xFFT6zqPLi.Z5NZPWXaO5RlfsOZ.5ay0x45E5Kp8ca',
    c.id, 'Avenida 6N # 23-45', 'CLIENTE', TRUE
FROM cities c
WHERE c.name = 'Cali'
ON CONFLICT (email) DO NOTHING;

INSERT INTO users (
    first_name, second_name, first_last_name, second_last_name,
    email, username, phone, password, city_id, address, role, enabled
)
SELECT
    'Laura', 'Isabel', 'Mendez', 'Castro',
    'laura.mendez@example.com', 'lauramendez', '3134567890',
    '$2a$10$.BriSU.VHeGs.eWvJs0lkeF.r9oY6Mu.5D7fj5mYLL.qMRYVf9e7S',
    c.id, 'Calle 72 # 11-45', 'CLIENTE', TRUE
FROM cities c
WHERE c.name = 'Bogota'
ON CONFLICT (email) DO NOTHING;

INSERT INTO users (
    first_name, second_name, first_last_name, second_last_name,
    email, username, phone, password, city_id, address, role, enabled
)
SELECT
    'Natalia', 'Andrea', 'Giraldo', 'Vargas',
    'natalia.giraldo@example.com', 'natalia.g', '3159876543',
    '$2a$10$yAHLY1l/EqrnbkXcQxwdfe5kwv5lrgzytRGYAgFntOdqx2DM81PJS',
    c.id, 'Carrera 48 # 18-35', 'CLIENTE', TRUE
FROM cities c
WHERE c.name = 'Medellin'
ON CONFLICT (email) DO NOTHING;

INSERT INTO users (
    first_name, second_name, first_last_name, second_last_name,
    email, username, phone, password, city_id, address, role, enabled
)
SELECT
    'Sofia', 'Valentina', 'Ramirez', 'Moreno',
    'sofia.ramirez@example.com', 'sofiaramirez', '3206543210',
    '$2a$10$itS5KZVkKesBnhDXGicb7OBqr67Hsvm6xYApw7a3RDnAZlBOFDgqm',
    c.id, 'Calle 84 # 51B-20', 'CLIENTE', TRUE
FROM cities c
WHERE c.name = 'Barranquilla'
ON CONFLICT (email) DO NOTHING;

-- Crear carritos para usuarios existentes por si se deshabilito el trigger.
INSERT INTO carts (user_id)
SELECT id FROM users
ON CONFLICT (user_id) DO NOTHING;

INSERT INTO products (
    name, description, price, stock, category_id, active, featured, new_collection, sold_count
) VALUES
(
    'Collar Lotus Rosado',
    'Collar artesanal rosado con acabado delicado para uso diario.',
    45000, 8, (SELECT id FROM categories WHERE slug = 'collares'),
    TRUE, TRUE, TRUE, 6
),
(
    'Collar Xiomara Fosil',
    'Collar colorido con dijes inspirados en piezas vintage y tonos aqua.',
    80000, 6, (SELECT id FROM categories WHERE slug = 'collares'),
    TRUE, TRUE, TRUE, 9
),
(
    'collar vibras',
    'Collar alegre con mostacillas de colores y charms dorados.',
    30000, 10, (SELECT id FROM categories WHERE slug = 'collares'),
    TRUE, TRUE, FALSE, 4
),
(
    'Set collares Mistica',
    'Set de collares delicados para combinar en capas con perla central.',
    55000, 7, (SELECT id FROM categories WHERE slug = 'collares'),
    TRUE, TRUE, TRUE, 11
),
(
    'pulsera_amar',
    'Pulsera artesanal con perlas y cristales suaves para uso cotidiano.',
    25000, 12, (SELECT id FROM categories WHERE slug = 'pulseras'),
    TRUE, TRUE, FALSE, 7
),
(
    'Set pulseras coloridas',
    'Set de pulseras ajustables con tonos vivos y detalles dorados.',
    50000, 9, (SELECT id FROM categories WHERE slug = 'pulseras'),
    TRUE, FALSE, FALSE, 5
),
(
    'anillos Ivory',
    'Anillos artesanales de mostacilla con acabado delicado y combinable.',
    30000, 15, (SELECT id FROM categories WHERE slug = 'anillos'),
    TRUE, TRUE, FALSE, 8
),
(
    'Llavero perla Chic',
    'Llavero con perlas, dije nacarado y herraje dorado.',
    40000, 11, (SELECT id FROM categories WHERE slug = 'llaveros'),
    TRUE, TRUE, FALSE, 3
);

INSERT INTO product_images (product_id, image_url, alt_text, main_image)
SELECT id, '/img/CollarXiomaraFosil.jpeg', name, TRUE
FROM products;

INSERT INTO favorites (user_id, product_id)
SELECT u.id, p.id
FROM users u
JOIN products p ON p.name IN ('Collar Lotus Rosado', 'pulsera_amar')
WHERE u.email = 'cliente1@salma.com'
ON CONFLICT (user_id, product_id) DO NOTHING;

INSERT INTO cart_items (cart_id, product_id, quantity, selected)
SELECT c.id, p.id, 1, TRUE
FROM carts c
JOIN users u ON u.id = c.user_id
JOIN products p ON p.name = 'Set pulseras coloridas'
WHERE u.email = 'cliente1@salma.com'
ON CONFLICT (cart_id, product_id) DO NOTHING;

INSERT INTO orders (user_id, status, total, shipping_cost, shipping_address, created_at)
SELECT id, 'PAGADO', 67000, 12000, address, CURRENT_TIMESTAMP - INTERVAL '3 days'
FROM users
WHERE email = 'cliente1@salma.com';

INSERT INTO orders (user_id, status, total, shipping_cost, shipping_address, created_at)
SELECT id, 'ENVIADO', 105000, 0, address, CURRENT_TIMESTAMP - INTERVAL '2 days'
FROM users
WHERE email = 'cliente1@salma.com';

INSERT INTO orders (user_id, status, total, shipping_cost, shipping_address, created_at)
SELECT id, 'ENTREGADO', 100000, 0, address, CURRENT_TIMESTAMP - INTERVAL '1 day'
FROM users
WHERE email = 'cliente2@salma.com';

INSERT INTO order_items (order_id, product_id, quantity, unit_price)
SELECT o.id, p.id, 1, p.price
FROM orders o
JOIN users u ON u.id = o.user_id
JOIN products p ON p.name = 'Set collares Mistica'
WHERE u.email = 'cliente1@salma.com' AND o.total = 67000;

INSERT INTO order_items (order_id, product_id, quantity, unit_price)
SELECT o.id, p.id, 1, p.price
FROM orders o
JOIN users u ON u.id = o.user_id
JOIN products p ON p.name = 'Collar Xiomara Fosil'
WHERE u.email = 'cliente1@salma.com' AND o.total = 105000;

INSERT INTO order_items (order_id, product_id, quantity, unit_price)
SELECT o.id, p.id, 1, p.price
FROM orders o
JOIN users u ON u.id = o.user_id
JOIN products p ON p.name = 'pulsera_amar'
WHERE u.email = 'cliente1@salma.com' AND o.total = 105000;

INSERT INTO order_items (order_id, product_id, quantity, unit_price)
SELECT o.id, p.id, 1, p.price
FROM orders o
JOIN users u ON u.id = o.user_id
JOIN products p ON p.name = 'Llavero perla Chic'
WHERE u.email = 'cliente2@salma.com' AND o.total = 100000;

INSERT INTO order_items (order_id, product_id, quantity, unit_price)
SELECT o.id, p.id, 2, p.price
FROM orders o
JOIN users u ON u.id = o.user_id
JOIN products p ON p.name = 'anillos Ivory'
WHERE u.email = 'cliente2@salma.com' AND o.total = 100000;

INSERT INTO return_requests (order_id, user_id, reason, status, created_at)
SELECT o.id, o.user_id, 'El producto no era la talla esperada y deseo coordinar la devolucion.', 'EN_REVISION', CURRENT_TIMESTAMP
FROM orders o
JOIN users u ON u.id = o.user_id
WHERE u.email = 'cliente2@salma.com' AND o.status = 'ENTREGADO'
LIMIT 1;

INSERT INTO reviews (user_id, product_id, rating, comment, approved, created_at)
SELECT u.id, p.id, 5, 'Muy lindo, llego bien empacado y se ve delicado.', TRUE, CURRENT_TIMESTAMP - INTERVAL '1 day'
FROM users u
JOIN products p ON p.name = 'Set collares Mistica'
WHERE u.email = 'cliente1@salma.com'
ON CONFLICT (user_id, product_id) DO NOTHING;

INSERT INTO reviews (user_id, product_id, rating, comment, approved, created_at)
SELECT u.id, p.id, 4, 'Los colores son bonitos y combina con muchas prendas.', TRUE, CURRENT_TIMESTAMP
FROM users u
JOIN products p ON p.name = 'anillos Ivory'
WHERE u.email = 'cliente2@salma.com'
ON CONFLICT (user_id, product_id) DO NOTHING;

-- VERIFICACION


SELECT 'cities' AS tabla, COUNT(*) AS total FROM cities
UNION ALL
SELECT 'categories', COUNT(*) FROM categories
UNION ALL
SELECT 'users', COUNT(*) FROM users
UNION ALL
SELECT 'products', COUNT(*) FROM products
UNION ALL
SELECT 'product_images', COUNT(*) FROM product_images
UNION ALL
SELECT 'carts', COUNT(*) FROM carts;
