-- SALMA ACCESORIOS
-- Script PostgreSQL completo para crear la base de datos normalizada del e-commerce.
-- En pgAdmin: crea primero la base salma_accesorios, abre Query Tool sobre esa base y ejecuta este script.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

DROP TABLE IF EXISTS review_images CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS favorites CASCADE;
DROP TABLE IF EXISTS cart_items CASCADE;
DROP TABLE IF EXISTS carts CASCADE;
DROP TABLE IF EXISTS product_images CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS cities CASCADE;

CREATE TABLE cities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    CONSTRAINT uk_city_name UNIQUE (name),
    CONSTRAINT chk_city_name CHECK (name ~ '^[A-Za-zÁÉÍÓÚáéíóúÑñ ]{2,80}$')
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(60) NOT NULL,
    second_name VARCHAR(60),
    first_last_name VARCHAR(60) NOT NULL,
    second_last_name VARCHAR(60) NOT NULL,
    email VARCHAR(120) NOT NULL,
    username VARCHAR(40) NOT NULL,
    phone VARCHAR(10) NOT NULL,
    password VARCHAR(255) NOT NULL,
    city_id BIGINT NOT NULL,
    address VARCHAR(160) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'CLIENTE',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_phone UNIQUE (phone),
    CONSTRAINT fk_users_city FOREIGN KEY (city_id) REFERENCES cities (id),
    CONSTRAINT chk_users_first_name CHECK (first_name ~ '^[A-Za-zÁÉÍÓÚáéíóúÑñ]{2,60}$'),
    CONSTRAINT chk_users_second_name CHECK (second_name IS NULL OR second_name ~ '^[A-Za-zÁÉÍÓÚáéíóúÑñ]{2,60}$'),
    CONSTRAINT chk_users_first_last_name CHECK (first_last_name ~ '^[A-Za-zÁÉÍÓÚáéíóúÑñ]{2,60}$'),
    CONSTRAINT chk_users_second_last_name CHECK (second_last_name ~ '^[A-Za-zÁÉÍÓÚáéíóúÑñ]{2,60}$'),
    CONSTRAINT chk_users_email CHECK (email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'),
    CONSTRAINT chk_users_username CHECK (username ~ '^[A-Za-z0-9._-]{4,40}$'),
    CONSTRAINT chk_users_phone CHECK (phone ~ '^3[0-9]{9}$'),
    CONSTRAINT chk_users_address CHECK (address ~ '^[A-Za-z0-9ÁÉÍÓÚáéíóúÑñ#.,\- ]{8,160}$'),
    CONSTRAINT chk_users_role CHECK (role IN ('ADMIN', 'CLIENTE'))
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    slug VARCHAR(100) NOT NULL,
    CONSTRAINT uk_categories_name UNIQUE (name),
    CONSTRAINT uk_categories_slug UNIQUE (slug),
    CONSTRAINT chk_categories_slug CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(1200) NOT NULL,
    price NUMERIC(12, 2) NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0,
    category_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    featured BOOLEAN NOT NULL DEFAULT FALSE,
    average_rating NUMERIC(3, 2) NOT NULL DEFAULT 0,
    sold_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT chk_products_price CHECK (price > 0),
    CONSTRAINT chk_products_stock CHECK (stock >= 0),
    CONSTRAINT chk_products_rating CHECK (average_rating >= 0 AND average_rating <= 5),
    CONSTRAINT chk_products_sold_count CHECK (sold_count >= 0)
);

CREATE TABLE product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    alt_text VARCHAR(140) NOT NULL,
    main_image BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_product_images_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT chk_product_images_url CHECK (length(trim(image_url)) >= 3),
    CONSTRAINT chk_product_images_alt CHECK (length(trim(alt_text)) >= 3)
);

CREATE TABLE carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    CONSTRAINT uk_carts_user UNIQUE (user_id),
    CONSTRAINT fk_carts_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    selected BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_cart_product UNIQUE (cart_id, product_id),
    CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES carts (id) ON DELETE CASCADE,
    CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT chk_cart_items_quantity CHECK (quantity > 0)
);

CREATE TABLE favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_favorite_user_product UNIQUE (user_id, product_id),
    CONSTRAINT fk_favorites_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_favorites_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    total NUMERIC(12, 2) NOT NULL DEFAULT 0,
    shipping_address VARCHAR(160) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_orders_total CHECK (total >= 0),
    CONSTRAINT chk_orders_shipping_address CHECK (length(trim(shipping_address)) >= 8),
    CONSTRAINT chk_orders_status CHECK (status IN ('PENDIENTE', 'PAGADO', 'ENVIADO', 'ENTREGADO', 'CANCELADO'))
);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL,
    CONSTRAINT uk_order_product UNIQUE (order_id, product_id),
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT chk_order_items_quantity CHECK (quantity > 0),
    CONSTRAINT chk_order_items_unit_price CHECK (unit_price > 0)
);

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    rating INTEGER NOT NULL,
    comment VARCHAR(800) NOT NULL,
    approved BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_review_user_product UNIQUE (user_id, product_id),
    CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_reviews_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT chk_reviews_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT chk_reviews_comment CHECK (length(trim(comment)) BETWEEN 8 AND 800)
);

CREATE TABLE review_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id BIGINT NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    CONSTRAINT fk_review_images_review FOREIGN KEY (review_id) REFERENCES reviews (id) ON DELETE CASCADE,
    CONSTRAINT chk_review_images_url CHECK (length(trim(image_url)) >= 3)
);

CREATE INDEX idx_users_email ON users (email);
CREATE INDEX idx_users_username ON users (username);
CREATE INDEX idx_users_city ON users (city_id);
CREATE INDEX idx_categories_slug ON categories (slug);
CREATE INDEX idx_products_name ON products (name);
CREATE INDEX idx_products_category ON products (category_id);
CREATE INDEX idx_products_featured ON products (featured);
CREATE INDEX idx_products_active ON products (active);
CREATE INDEX idx_products_sold_count ON products (sold_count DESC);
CREATE INDEX idx_products_search ON products USING gin (to_tsvector('spanish', name || ' ' || description));
CREATE INDEX idx_product_images_product ON product_images (product_id);
CREATE UNIQUE INDEX uk_product_one_main_image ON product_images (product_id) WHERE main_image = TRUE;
CREATE INDEX idx_cart_items_cart ON cart_items (cart_id);
CREATE INDEX idx_cart_items_selected ON cart_items (selected);
CREATE INDEX idx_favorites_user ON favorites (user_id);
CREATE INDEX idx_favorites_product ON favorites (product_id);
CREATE INDEX idx_orders_user ON orders (user_id);
CREATE INDEX idx_orders_status ON orders (status);
CREATE INDEX idx_orders_created_at ON orders (created_at DESC);
CREATE INDEX idx_order_items_order ON order_items (order_id);
CREATE INDEX idx_order_items_product ON order_items (product_id);
CREATE INDEX idx_reviews_product ON reviews (product_id);
CREATE INDEX idx_reviews_user ON reviews (user_id);
CREATE INDEX idx_reviews_approved ON reviews (approved);
CREATE INDEX idx_review_images_review ON review_images (review_id);

CREATE OR REPLACE FUNCTION refresh_product_average_rating()
RETURNS TRIGGER AS $$
DECLARE
    affected_product_id BIGINT;
BEGIN
    affected_product_id := COALESCE(NEW.product_id, OLD.product_id);

    UPDATE products
    SET average_rating = COALESCE((
        SELECT ROUND(AVG(rating)::numeric, 2)
        FROM reviews
        WHERE product_id = affected_product_id
          AND approved = TRUE
    ), 0)
    WHERE id = affected_product_id;

    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_reviews_refresh_rating
AFTER INSERT OR UPDATE OR DELETE ON reviews
FOR EACH ROW
EXECUTE FUNCTION refresh_product_average_rating();

INSERT INTO cities (name)
VALUES ('Bogota'), ('Medellin'), ('Cali'), ('Barranquilla'), ('Cartagena')
ON CONFLICT (name) DO NOTHING;

INSERT INTO categories (name, slug)
VALUES
    ('Collares', 'collares'),
    ('Pulseras', 'pulseras'),
    ('Anillos', 'anillos'),
    ('Llaveros', 'llaveros'),
    ('Otros', 'otros')
ON CONFLICT (slug) DO NOTHING;

-- Hash BCrypt de Admin123*
INSERT INTO users (
    first_name, first_last_name, second_last_name, email, username, phone,
    password, city_id, address, role
)
SELECT
    'Admin', 'Salma', 'Accesorios', 'admin@salma.com', 'admin', '3000000000',
    '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',
    c.id, 'Calle 1 # 1-1', 'ADMIN'
FROM cities c
WHERE c.name = 'Bogota'
ON CONFLICT (email) DO NOTHING;

-- Usuarios cliente de prueba. Contraseña en la app: Cliente123*
-- Si quieres hashes reales generados por BCrypt, deja que DataInitializer los cree al iniciar Spring Boot.
